language: python
sudo: required
dist: xenial
python:
- '3.7'
- '3.6'
- '3.5'
before_install: sudo rm -f /etc/boto.cfg
install: make init
script:
- export BOTO_CONFIG=/dev/null
- make tests
deploy:
  provider: pypi
  user: lior.miz
  password:
    secure: sqNwNRU1pFwU79FhzGlr91H7kGDFpyJbRfeaJd7Af8Noe0iFlsiWwEeQWQo5fZE5vrNU7q6C5Z6XeXCFH7Yzbs0kAz+BEHdLk5qHJCy+ZuysWWIYp2Lhuqy372uaq0XIYeUGDGw1g2LsN81Y0UL/qw0E07zhIa+9cAS9+vjcvzWfQy2/3hNlwJnh8RobryKqOW9j2CdblpvoMZGpRQ1WlY829Yb0sZDCI+9WrJZ0QHnlmdVFk1KmpQmHffZmuHwaLYsSDVnkrdE/1ljiOJYzs0apRi/bge355Mfb12LUNhHz9PrKsPzqZYgDMumj+6HwD8euTFJyPKfjr2YAbVmsRLCjer5Xsh7a8dKScToxmdJ9pcoyClAMbq8t+s8avEDdMQx9DEq75cpUJIbGws9EI54MS6Hjpu5EhNw101KrZRCIIaodToFyf3HZQr0kaJrRn2ylgu+XJWk8PwGIaFuSbh9Yl6NbcBUld17p6n3KdYzBNVQNPpViPF4kM6JytrRpCTxl1GX69o55qVzjYpR4+IQNzDd8Oifg/1EhBWBKODQ3x/o1CVi3lKS9h/VN3qmvKlI0ZeCka1cwBA+Hbdf8YuJwk5aBDk3TO/WoxK8inO75By6kH7TVWltFE46tYI8tjY+kFUXK5jCMvgeQnRYbQYJABdppfzUBc3A2ow3bUdA=
  on:
    python: 3.6
    distributions: sdist bdist_wheel
    repo: liormizr/s3path
    branch: master
