name: S3Path Tester

on:
  push:
    branchs:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo rm -f /etc/boto.cfg
          make init
      - name: Run Tests
#         env: BOTO_CONFIG=/dev/null
        run: make tests

